apiVersion: tekton.dev/v1
kind: Pipeline

metadata:
  name: payment-ci-pipeline

spec:

  params:

  - name: git-url
    type: string
    default: "https://github.com/neyagopi75/k8s-payment-pipeline"

  - name: git-revision
    type: string
    default: "main"

  - name: image-repository
    type: string
    default: "artifactory.company.com/payment-system"

  - name: image-tag
    type: string
    default: "latest"

  workspaces:

  - name: source-workspace

  tasks:

  - name: clone-source

    taskRef:
      name: git-clone

    params:

    - name: url
      value: $(params.git-url)

    - name: revision
      value: $(params.git-revision)

    workspaces:

    - name: output
      workspace: source-workspace

  - name: build-image

    runAfter:
    - clone-source

    taskRef:
      name: buildah

    params:

    - name: IMAGE
      value: $(params.image-repository):$(params.image-tag)

    - name: DOCKERFILE
      value: ./Dockerfile

    - name: CONTEXT
      value: .

    workspaces:

    - name: source
      workspace: source-workspace

  - name: push-image

    runAfter:
    - build-image

    taskRef:
      name: push-artifactory

    params:

    - name: IMAGE
      value: $(params.image-repository):$(params.image-tag)

    workspaces:

    - name: source
      workspace: source-workspace
